### ISSUE TITLE
Issue when running command.

### ISSUE THREAD

**Issue by deavmi** [deavmi/DuckIt#4]
When trying to run the command `python3 duckit.py hello` I get the following error:

<hr>

```Bash
$ python duckit.py test

Traceback (most recent call last):
File "duckit.py", line 32, in <module>
init()
File "duckit.py", line 30, in init
else: search(arg)
File "duckit.py", line 20, in search
subprocess.call([app.browser, "https://duckduckgo.com/?q=" + query])
File "/opt/python/3.3.5/lib/python3.3/subprocess.py", line 523, in call
with Popen(*popenargs, **kwargs) as p:
File "/opt/python/3.3.5/lib/python3.3/subprocess.py", line 819, in __init__
restore_signals, start_new_session)
File "/opt/python/3.3.5/lib/python3.3/subprocess.py", line 1448, in _execute_child
raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
````

Eveything else looks fine, It seems to have to do with the code that is calling firefox to start with the string attached to it telling FireFox (our testbench browser) to naviagte to the page we specified as a command-line argument.

<hr>

The config file is in the right place `~/.config/duckit/config.txt` with the contents of the file being:

````
browser=firefox
````

<hr>

I don't know what to do, but everything looks fine3.

**Comment by deavmi** [comment]
This was fixed in tow commits, this one 073f02060947740f6d034b919a121ad9fb45b3cd and this one 29276d5c8abb63da313f610de9cf9e21cc4da04b .
